name: Deploy to PyPI

on:
  # allows to manually run the job at any time
  workflow_dispatch:
  # run on every push on the master branch
  push:
    branches:
      - main

jobs:
  build:
    environment:
      name: pypi
      url: https://pypi.org/project/assert-files
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    name: Build and validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          python setup.py pytest
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Validate build
        run: |
          twine check dist/*
      # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
